# Generated by Django 4.1.7 on 2023-11-17 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alergie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Klant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gezinsnaam", models.CharField(max_length=100)),
                ("volwassenen", models.IntegerField()),
                ("kinderen", models.IntegerField()),
                ("babies", models.IntegerField()),
                ("postcode", models.CharField(max_length=50)),
                ("varkesvlees", models.BooleanField()),
                ("vegataries", models.BooleanField()),
                ("veganistisch", models.BooleanField()),
                (
                    "alergieën",
                    models.ManyToManyField(related_name="klant", to="klanten.alergie"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BSN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("BSN", models.IntegerField()),
                ("volledigenaam", models.CharField(max_length=100)),
                (
                    "klant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="klanten.klant",
                    ),
                ),
            ],
        ),
    ]
