# Generated by Django 4.1.7 on 2023-11-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klanten', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klant',
            name='alergieën',
            field=models.ManyToManyField(blank=True, null=True, related_name='klant', to='klanten.alergie'),
        ),
    ]
