# Generated by Django 4.1.7 on 2023-11-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("directie", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leverancier",
            name="leveringsdatum",
            field=models.DateField(blank=True, null=True),
        ),
    ]
