# Generated by Django 4.1.7 on 2023-11-29 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directie', '0002_leverancier_leveringsfrequentie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leverancier',
            name='leveringsfrequentie',
        ),
    ]
