# Generated by Django 4.1.7 on 2023-12-04 08:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("directie", "0002_alter_leverancier_leveringsdatum"),
        ("directie", "0003_remove_leverancier_leveringsfrequentie"),
    ]

    operations = []
