from .stock_employe import StockEmployeView
from .add_stock import AddStockView
from .update_stock import UpdateStockView
from .product_item_view import ProductItemView
from .add_product_item import AddProductItem
from .update_product_item import UpdateProductItem
from .product_item_verwijderen import DeleteProductItem
from .pakket import PakketView
from .pakket_kiezen import ChoicePackage
from .toevoegen_aan_pakket import ToevoegenPakketView
from .pakket_detail import PakketDetailView
from .pakket_verwijderen import VerwijderenPakketView