# Generated by Django 4.1.7 on 2023-11-17 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("directie", "0001_initial"),
        ("klanten", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Catagorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("omschrijving", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("EAN", models.IntegerField()),
                ("afbeelding", models.ImageField(null=True, upload_to="images/")),
                ("varkesvlees", models.BooleanField()),
                ("vegataries", models.BooleanField()),
                ("veganistisch", models.BooleanField()),
                ("voorraad", models.IntegerField(default=0)),
                (
                    "catagorieën",
                    models.ManyToManyField(
                        related_name="product", to="magazijn.catagorie"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("leverings_datum", models.DateField(auto_now_add=True)),
                ("houdsbaarheiddatum", models.DateField()),
                ("status", models.IntegerField()),
                (
                    "leverancier",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="directie.leverancier",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="magazijn.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pakket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uitgiftdatum", models.DateField()),
                (
                    "gezinsnaam",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="klanten.klant",
                    ),
                ),
                (
                    "productitem",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="magazijn.productitem",
                    ),
                ),
            ],
        ),
    ]
