# Generated by Django 4.1.7 on 2023-11-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magazijn", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productitem",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Goed"),
                    (2, "Beschadigd"),
                    (3, "Verlopen"),
                    (4, "Verdwenen"),
                ],
                default=1,
            ),
        ),
    ]
