# Generated by Django 4.1.7 on 2023-11-22 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("magazijn", "0002_alter_productitem_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pakket",
            name="productitem",
        ),
        migrations.AddField(
            model_name="productitem",
            name="pakket",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="magazijn.pakket",
            ),
        ),
        migrations.AlterField(
            model_name="productitem",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Goed"),
                    (2, "in pakket"),
                    (3, "Verlopen"),
                    (4, "Verdwenen"),
                ],
                default=1,
            ),
        ),
    ]
