# Generated by Django 4.1.7 on 2023-11-22 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magazijn", "0003_remove_pakket_productitem_productitem_pakket_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pakket",
            name="uitgiftdatum",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 11, 29, 12, 24, 50, 844924, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
