# Generated by Django 4.1.7 on 2023-11-23 08:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("klanten", "0001_initial"),
        ("magazijn", "0005_pakket_status_alter_pakket_uitgiftdatum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pakket",
            name="gezinsnaam",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="klanten.klant",
            ),
        ),
        migrations.AlterField(
            model_name="pakket",
            name="uitgiftdatum",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 11, 30, 8, 26, 10, 311859, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
