# Generated by Django 4.1.7 on 2023-11-23 08:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("directie", "0001_initial"),
        ("magazijn", "0006_alter_pakket_gezinsnaam_alter_pakket_uitgiftdatum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pakket",
            name="uitgiftdatum",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 11, 30, 8, 29, 54, 634181, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="productitem",
            name="leverancier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="directie.leverancier",
            ),
        ),
        migrations.AlterField(
            model_name="productitem",
            name="pakket",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="magazijn.pakket",
            ),
        ),
        migrations.AlterField(
            model_name="productitem",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="magazijn.product",
            ),
        ),
    ]
