# Generated by Django 4.1.7 on 2023-11-23 08:32

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("magazijn", "0008_alter_pakket_uitgiftdatum"),
    ]

    operations = [
        migrations.AddField(
            model_name="pakket",
            name="aangemaakt_op",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pakket",
            name="uitgiftdatum",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 11, 30, 8, 32, 24, 12011, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
