# Generated by Django 4.1.7 on 2023-11-27 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magazijn", "0010_alter_pakket_uitgiftdatum_alter_productitem_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pakket",
            name="aangemaakt_op",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="pakket",
            name="uitgiftdatum",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 12, 4, 8, 39, 3, 2974, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
