# Generated by Django 4.1.7 on 2023-11-28 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazijn', '0013_alter_pakket_aangemaakt_op_alter_pakket_uitgiftdatum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pakket',
            name='status',
            field=models.IntegerField(choices=[(1, 'niet opgehaald'), (2, 'opgehaald')], default=1),
        ),
        migrations.AlterField(
            model_name='pakket',
            name='uitgiftdatum',
            field=models.DateField(default=datetime.datetime(2023, 12, 5, 8, 44, 34, 136516, tzinfo=datetime.timezone.utc)),
        ),
    ]
