# Generated by Django 4.1.7 on 2023-11-28 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazijn', '0014_alter_pakket_status_alter_pakket_uitgiftdatum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pakket',
            name='uitgiftdatum',
            field=models.DateField(default=datetime.datetime(2023, 12, 5, 9, 7, 57, 952414, tzinfo=datetime.timezone.utc)),
        ),
    ]
