# Generated by Django 4.1.7 on 2023-11-30 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magazijn", "0016_alter_pakket_uitgiftdatum_alter_productitem_pakket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pakket",
            name="uitgiftdatum",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 12, 7, 7, 46, 59, 271411, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="varkesvlees",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="veganistisch",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="vegataries",
            field=models.BooleanField(default=False),
        ),
    ]
