# Generated by Django 4.1.7 on 2023-12-04 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazijn', '0018_alter_pakket_uitgiftdatum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pakket',
            name='uitgiftdatum',
            field=models.DateField(default=datetime.datetime(2023, 12, 11, 10, 3, 3, 715406, tzinfo=datetime.timezone.utc)),
        ),
    ]
