# Generated by Django 4.1.7 on 2023-12-06 07:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("directie", "0004_merge_20231204_0917"),
        ("magazijn", "0019_alter_pakket_uitgiftdatum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pakket",
            name="uitgiftdatum",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 12, 13, 7, 51, 0, 204694, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="productitem",
            name="leverancier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_items",
                to="directie.leverancier",
            ),
        ),
        migrations.AlterField(
            model_name="productitem",
            name="pakket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_items",
                to="magazijn.pakket",
            ),
        ),
        migrations.AlterField(
            model_name="productitem",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_items",
                to="magazijn.product",
            ),
        ),
    ]
